name: ci simple

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{DOCKER_USER,,}}/arch-stuff:latest docker/Dockerfile.

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{DOCKER_USER,,}}/arch-stuff:latest