name: ci simple

on:
  push:
    branches:
      - main

permissions:
  packages: write

env:
  DOCKER_USER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          DOCKER_USER_LOWER=${DOCKER_USER,,}
          echo "Docker user lower: $DOCKER_USER_LOWER"
          
          docker build -t ghcr.io/$DOCKER_USER_LOWER/arch-stuff:latest -f docker/Dockerfile .
          
          docker push ghcr.io/$DOCKER_USER_LOWER/arch-stuff:latest
